### ISSUE TITLE
Complete n00b question -- apologies

### ISSUE THREAD

**Issue by rstudner** [fortunejs/fortune-postgres#19]
So i'm just getting started on an expressjs backend.. i'm using a postgresdb and of course am making use of Sequelize.

Does this REPLACE Sequelize or do I use them in conjunction somehow?

I'm very early, so making changes now would be easy -- and I really like the look of the fortunejs project (and want a json-api compliant API)

(And there is Bookshelf hah.  Man i'm new to this particular nodejs ORM world)

**Comment by sapeien** [comment]
This would replace Sequelize, Bookshelf, Knex, etc. What the `fortune-postgres` module does is it translates requests from Fortune into raw pgSQL and uses the `pg` driver directly.

It would be most similar to Knex but instead of using an SQL-like chaining API, it uses the same adapter interface that would be used for non-relational databases as well. An important distinction is that Fortune is not coupled with relational databases, which makes it work in the browser (IndexedDB) and with NoSQL (MongoDB).

Not everything that is possible with pgSQL is built-in to this adapter, for edge cases it's recommended to [use the client provided by the `pg` driver directly](https://github.com/fortunejs/fortune-postgres#internal-usage).

**Comment by rstudner** [comment]
Thank you so much for the thoughtful and complete answer :)

I'm going to try to port my code over to fortunejs later today.  I won't have any highly complicated things/feature needs.  I mostly just want to take a sane postgres DB, run some queries on it, and output jsonapi formatted responses for an EmberUI (which of course loves jsonapi by default).

Does Fortunejs create the db tables if they don't exist / support fixture capabilities? (not a big deal, just figured i'd ask).

**Comment by sapeien** [comment]
this adapter does all of the table setup, yes. however you need to at least create the database externally, as stated in the readme.

there's no fixtures built-in but I'm sure that SQL dumps work fine for that purpose.
