### ISSUE TITLE
Auto incremental id

### ISSUE THREAD

**Issue by mak1986** [fortunejs/fortune-postgres#7]
When making a post request, It won't auto increment the primary key. With these options below, it will try to insert a null value in the field instead. 
```javascript
options: {
    url: `postgres://${username}:${password}@${host}:${port}/${db}`,
    primaryKeyType: Number,
    generatePrimaryKey: null
}
```

This is what it says:
Unhandled rejection error: null value in column "id" violates not-null constraint

P.S. Happy New Year :)

**Comment by mak1986** [comment]
Oh just saw the related post. Sorry :)

**Comment by mak1986** [comment]
Seems like the id field need to be removed just before inserting into the table.

**Comment by 0x8890** [comment]
I think `Number` isn't the right type for auto-incrementing in Postgres, you actually want `'serial'` or `'bigserial'`. 

Anyways, this should be fixed in commits https://github.com/fortunejs/fortune-postgres/commit/b488bfebcb3d5dd6c767fcd36b6b0e4d1f1dd02c and https://github.com/fortunejs/fortune-postgres/commit/4d63a0b4c21c849807a23cd698a66bed5bb21ce2.
